### ISSUE TITLE
Don't know how to build task 'assets:clobber'

### ISSUE THREAD

**Issue by mockdeep** [rails/dartsass-rails#13]
When I install the `dartsass-rails` gem, it causes my Rake tasks to break:

```sh
$ rails dartsass:install --trace
rails aborted!
Don't know how to build task 'assets:clobber' (See the list of available tasks with `rails --tasks`)
Did you mean?  assets:clean
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:405:in `[]'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/dartsass-rails-0.3.0/lib/tasks/clobber.rake:9:in `<main>'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `each'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `run_tasks_blocks'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/application.rb:504:in `block in run_tasks_blocks'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine/railties.rb:15:in `each'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine/railties.rb:15:in `each'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/application.rb:504:in `run_tasks_blocks'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/engine.rb:464:in `load_tasks'
/home/fletch/Dropbox/projects/web_apps/questlog/Rakefile:3:in `<main>'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/command.rb:51:in `invoke'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/railties-7.0.2.2/lib/rails/commands.rb:18:in `<main>'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/fletch/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
```

It seems to vary. On another project it instead complains `Don't know how to build task 'assets:precompile'`. [Here's an example](https://github.com/mockdeep/lmkw/tree/rf-dartsass). You can see it failing [the CI build here](https://app.circleci.com/pipelines/github/mockdeep/lmkw/2019/workflows/97ce0219-43c9-4f62-8b06-c5636622a212/jobs/2035).

**Comment by mockdeep** [comment]
As far as I know, I'm not doing anything weird with Rails tasks. The tasks are available to me if I try to run them on `main`.

**Comment by maxhoffmann** [comment]
I’m running into the same issue and am trying to figure out what’s happening. Any help would be appreciated 🙏

**Comment by maxhoffmann** [comment]
Running `rails --tasks` I saw that none of the `assets:` tasks where available. `bundle add sprockets-rails` fixed that for me

**Comment by maxhoffmann** [comment]
Okay, finally found the upgrade guide that I found a while ago but couldn’t locate it anymore: https://github.com/rails/propshaft/blob/main/UPGRADING.md

This helped in making the JS and Sass work 😮‍💨

**Comment by airblade** [comment]
I believe you need `propshaft` (or `sprockets-rails`, depending on your situation).

**Comment by dhh** [comment]
Correct. dartsass-rails needs an asset pipeline.

**Comment by mockdeep** [comment]
@dhh I have `sprockets-rails` installed. It's a dependency of Rails 6.1. We've been using sprockets with `sass-rails` and that has been working fine. We're able to run `rails assets:precompile` with that.

**Comment by mockdeep** [comment]
NM, I see it the dependency was removed in Rails 7.

**Comment by bogdan** [comment]
> Correct. dartsass-rails needs an asset pipeline.

@dhh does it mean that `sprockets-rails` should be a dependency of this gem?

**Comment by dhh** [comment]
No. It can use propshaft which is the new default. Don't think we need to do anything here.
